name: survival-unlocked
main: com.uravgcode.survivalunlocked.SurvivalUnlocked
bootstrapper: com.uravgcode.survivalunlocked.SurvivalUnlockedBootstrap
folia-supported: true
version: ${version}
api-version: '1.21.10'

description: vanilla friendly survival gameplay improvements
website: 'https://uravgcode.com'
authors: [ UrAvgCode ]
