name: survival-unlocked
main: com.uravgcode.survivalunlocked.SurvivalUnlocked
folia-supported: true
version: ${version}
api-version: '1.21.8'

description: vanilla friendly survival gameplay improvements
website: 'https://uravgcode.com'
authors: [ UrAvgCode ]
