[versions]
paper-api = "26.3.build.+"
paperweight = "2.0.0-beta.23"
resource-factory = "1.4.0"
run-task = "3.1.0"

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
resource-factory = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resource-factory" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
